### ISSUE TITLE
should add `.npmignore`

### ISSUE THREAD

**Issue by gucong3000** [npm/mute-stream#12]
The file that should not appear in the [compressed package](https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz)
![image](https://user-images.githubusercontent.com/1171691/42628181-e0edef2a-8601-11e8-88c7-21ee7245ee68.png)

**Comment by G-Rath** [comment]
Just FYI this was resolved in [`3447b66`](https://github.com/npm/mute-stream/commit/3447b665c17428fb99b75bede932658bb19402a4).
