### ISSUE TITLE
New admin?

### ISSUE THREAD

**Issue by gangstead** [npm/mute-stream#7]
@isaacs I know you are busy running npm, but can you add an admin to this repo a new collaborator for the npm package to publish fixes?  I'm willing to be that admin, but happy if you nominate anyone else.  Currently #3 is revealing itself in a dependency 3 levels down in my project.  My project uses [prompt](https://www.npmjs.com/package/prompt) which uses [read](https://www.npmjs.com/package/read) (another of your packages) which uses mute-stream.

I think this might be representative of an emerging issue with NPM itself.  What happens to packages that are essentially abandonware?  mute-stream is a good package, it just needs a small PR merged in and a patch released.  What is the @npm / NPM Inc approved solution for this?
Current solutions that come to mind feel bad:
-  Pollute the NPM registry namespace with new packages  `mute-stream-2`, `mute-stream-active`, `mute-stream-active-2` and let new users suffer the folly of relying on the package with the obvious name that is no longer maintained?
- Fork every abandoned project to merge a few patches and include my fork repo as a dependency in my package.json.  That removes all the benefit of the NPM registry. It also creates overhead and I have to go scouting through forks to find other bug fixes to merge into my fork which limits the benefit of having a registry.  This solution fixes my immediate problem but doesn't help the community.  In my particular case I have to fork two levels of projects to fix my issue.
- Fork and publish under a scoped package?  This cheats anyone else from benefitting from my work since it will be impossible to [find via search](https://github.com/npm/npm/issues/8244).

These all feel bad because they create a lot of duplicated work by anyone who needs to fix a package and add confusion to the system.  Maybe there should be some way for the community to vote on which repo an NPM package points to or a way to nominate a replacement repo if an owner becomes unresponsive?

**Comment by isaacs** [comment]
Thanks for the nudge.  You're absolutely right.

This module is part of the npm cli program, but I seem to have missed it in moving things over to the organization.

I've added @othiym23, @iarna, and @zkat as publishers on npm, and moved the repo over to the @npm organization, as well as landing the outstanding PRs.

It should be easier to keep track of, now.  If they decide that they want it to be externally managed, they can make the call to give it away.  If we weren't using it, I'd probably be happy to just give it to you.

My apologies for the long response time leading to duplicated work.  :(  Let me know if there's anything else necessary.
